const STICKER_ROOT = '/stickers/puppysoft';
const RECENT_STORAGE_PREFIX = 'vichat.stickers.recent.v1';

const packDefinitions = [
  {
    id: 'positive',
    label: 'Tích cực',
    color: '#2f9e44',
    icon: 'fa-thumbs-up',
    items: [
      ['Tuyệt vời!', 'tuyet voi tot lam'],
      ['OK!', 'ok dong y'],
      ['Hiểu rồi!', 'hieu roi'],
      ['Cảm ơn!', 'cam on thanks'],
      ['Tốt lắm!', 'tot lam thumbs up'],
      ['Chúc mừng!', 'chuc mung congratulations'],
      ['Yêu thích!', 'yeu thich love'],
      ['Quá đỉnh!', 'qua dinh cool'],
    ],
  },
  {
    id: 'response',
    label: 'Phản hồi',
    color: '#1672c4',
    icon: 'fa-reply',
    items: [
      ['Đồng ý!', 'dong y agree'],
      ['Got it!', 'got it'],
      ['Chắc chắn!', 'chac chan sure'],
      ['Sẽ làm ngay!', 'se lam ngay doing'],
      ['Đã nhận!', 'da nhan received'],
      ['Đang xử lý!', 'dang xu ly processing'],
      ['Copy that!', 'copy that'],
      ['Ổn áp!', 'on ap good'],
    ],
  },
  {
    id: 'neutral',
    label: 'Trung lập',
    color: '#65717b',
    icon: 'fa-circle-question',
    items: [
      ['Hmm...', 'hmm suy nghi'],
      ['Để mình xem', 'de minh xem look'],
      ['Đang xem xét', 'dang xem xet review'],
      ['Chờ chút nhé', 'cho chut nhe wait'],
      ['Không rõ', 'khong ro unclear'],
      ['Có thể', 'co the maybe'],
      ['Tạm ổn', 'tam on okay'],
      ['...', 'im lang neutral'],
    ],
  },
  {
    id: 'attention',
    label: 'Cần hỗ trợ',
    color: '#c95d2e',
    icon: 'fa-life-ring',
    items: [
      ['Giúp mình với!', 'giup minh voi help'],
      ['Có vấn đề!', 'co van de problem'],
      ['Quan trọng!', 'quan trong important'],
      ['Lưu ý nhé!', 'luu y attention'],
      ['Hạn chót!', 'han chot deadline'],
      ['Theo dõi nhé!', 'theo doi monitor'],
      ['Cần thêm info', 'can them info'],
      ['Ping mình nhé!', 'ping minh nhe'],
    ],
  },
  {
    id: 'emotions',
    label: 'Cảm xúc',
    color: '#c43d3d',
    icon: 'fa-face-smile',
    items: [
      ['Haha!', 'haha vui cuoi'],
      ['^^', 'smile vui'],
      ['Hihi', 'hihi vui'],
      ['Ồ wow!', 'oh wow ngac nhien'],
      ['Buồn quá', 'buon qua sad'],
      ['Mệt rồi', 'met roi tired'],
      ['Căng quá', 'cang qua stressed'],
      ['Thất vọng', 'that vong disappointed'],
    ],
  },
  {
    id: 'quick-actions',
    label: 'Hành động nhanh',
    color: '#7450b8',
    icon: 'fa-bolt',
    items: [
      ['Approved!', 'approved duyet'],
      ['Send it!', 'send it gui'],
      ['Later nhé', 'later nhe sau'],
      ['Ghim lại', 'ghim lai pin'],
      ['Reject', 'reject tu choi'],
      ['Chuyển tiếp', 'chuyen tiep forward'],
      ['Đánh dấu', 'danh dau mark'],
      ['Thêm vào', 'them vao add'],
    ],
  },
  {
    id: 'chick',
    label: 'Gà con',
    color: '#e39a25',
    icon: 'fa-egg',
    items: [
      ['Hello', 'hello xin chao chao'],
      ['Haha', 'haha cuoi vui'],
      ['Ôi', 'oi bat ngo ngac nhien'],
      ['Ngủ đi', 'ngu di chuc ngu ngon'],
      ['Wow', 'wow kinh ngac'],
      ['Sốc', 'soc choang'],
      ['Ngon', 'ngon an an ngon'],
      ['Giận rồi', 'gian roi tuc gian'],
      ['Ngại ghê', 'ngai ghe xau ho'],
      ['Vui nha', 'vui nha hanh phuc'],
      ['Mệt quá', 'met qua buon ngu'],
      ['Tự tin', 'tu tin cool'],
      ['Please', 'please lam on xin do'],
      ['Đang nghĩ', 'dang nghi suy nghi'],
      ['Thương', 'thuong yeu tim'],
      ['Tạm biệt', 'tam biet bye bye'],
    ],
  },
  {
    id: 'bunny',
    label: 'Thỏ hồng',
    color: '#d95b8a',
    icon: 'fa-heart',
    items: [
      ['Xin chào', 'xin chao hello'],
      ['Yayyy', 'yay vui mung'],
      ['Huhu', 'huhu khoc buon'],
      ['Ngủ ngon', 'ngu ngon chuc ngu ngon'],
      ['Ủa?', 'ua hoi bat ngo'],
      ['Hả trời', 'ha troi ngac nhien'],
      ['No no', 'no no tu choi'],
      ['Dỗi', 'doi gian hon'],
      ['Thích quá', 'thich qua yeu thich'],
      ['Xấu hổ', 'xau ho ngai'],
      ['Đỉnh', 'dinh cool ngau'],
      ['Lười', 'luoi nghi ngoi'],
      ['Xin đó', 'xin do lam on'],
      ['Suy nghĩ', 'suy nghi dang nghi'],
      ['Yêu nè', 'yeu ne tim yeu'],
      ['Bye bye', 'bye bye tam biet'],
    ],
  },
  {
    id: 'frog',
    label: 'Ếch xanh',
    color: '#5a9c54',
    icon: 'fa-frog',
    items: [
      ['Chào nha', 'chao nha hello'],
      ['Hehe', 'hehe haha cuoi'],
      ['Buồn ghê', 'buon ghe buon khoc'],
      ['Ngủ thôi', 'ngu thoi chuc ngu ngon'],
      ['Bất ngờ', 'bat ngo kinh ngac'],
      ['Khó hiểu', 'kho hieu suy nghi'],
      ['Ăn nè', 'an ne do an ngon'],
      ['Cáu', 'cau gian tuc'],
      ['Ngại', 'ngai xau ho'],
      ['Quá đã', 'qua da vui sung'],
      ['Oải', 'oai met moi'],
      ['Tự hào', 'tu hao proud'],
      ['Làm ơn', 'lam on please'],
      ['Hmm...', 'hmm suy nghi'],
      ['Tim nè', 'tim ne yeu thuong'],
      ['Tạm biệt', 'tam biet bye bye'],
    ],
  },
  {
    id: 'cat',
    label: 'Mèo cam',
    color: '#df7c2c',
    icon: 'fa-cat',
    items: [
      ['Alooo', 'alooo alo xin chao'],
      ['Quẩy lên', 'quay len vui nhay'],
      ['Khóc luôn', 'khoc luon buon khoc'],
      ['Ngủ đấy', 'ngu day chuc ngu ngon'],
      ['Ui trời', 'ui troi bat ngo'],
      ['Ủa alo', 'ua alo hoi'],
      ['Ngon quá', 'ngon qua an ngon'],
      ['Gừ', 'gu gian tuc'],
      ['Mắc cỡ', 'mac co xau ho'],
      ['Vui ghê', 'vui ghe haha'],
      ['Buồn ngủ', 'buon ngu met'],
      ['Tự hào', 'tu hao proud'],
      ['Năn nỉ', 'nan ni xin do'],
      ['Để coi', 'de coi xem xet'],
      ['Yêu yêu', 'yeu yeu tim'],
      ['Baiii', 'baiii bye bye'],
    ],
  },
  {
    id: 'frog-v2',
    label: 'Ếch xanh vui nhộn',
    color: '#66a80f',
    icon: 'fa-frog',
    items: [
      ['Ủa chào', 'ua chao hello'],
      ['Khịa nhẹ', 'khia nhe ca khia'],
      ['Cái gì cơ?', 'cai gi co bat ngo'],
      ['Nghe vô lý', 'nghe vo ly khong hop ly'],
      ['Tới công chuyện', 'toi cong chuyen khoc buon'],
      ['Ủa rồi sao?', 'ua roi sao hoi'],
      ['Mlem mlem', 'mlem mlem an ngon'],
      ['Căng nha', 'cang nha gian'],
      ['Ngại ghê', 'ngai ghe xau ho'],
      ['Đỉnh chóp', 'dinh chop cool'],
      ['Xỉu ngang', 'xiu ngang met'],
      ['Tự hào ghê', 'tu hao proud'],
      ['Xin vía', 'xin via cau may'],
      ['Suyyyy', 'suy suy nghi'],
      ['Tim nè', 'tim ne yeu thuong'],
      ['Biến đây', 'bien day bye'],
    ],
  },
  {
    id: 'corgi',
    label: 'Corgi lém lỉnh',
    color: '#d97706',
    icon: 'fa-dog',
    items: [
      ['Alo alo', 'alo alo xin chao'],
      ['Tăng ca à?', 'tang ca deadline'],
      ['Không ổn rồi', 'khong on roi lo lang'],
      ['Tui chịu', 'tui chiu dau hang'],
      ['Đói xỉu', 'doi xiu an ngon'],
      ['Quẩy lên', 'quay len vui'],
      ['Like mạnh', 'like manh yeu thich'],
      ['Lườm cái', 'luom cai gian'],
      ['Ê đừng', 'e dung stop'],
      ['Nghe chưa', 'nghe chua hoi'],
      ['Cảm động', 'cam dong khoc'],
      ['Cứu tui', 'cuu tui help'],
      ['Đi thôi', 'di thoi len duong'],
      ['Đợi xíu', 'doi xiu cho doi'],
      ['Ngáo ngơ', 'ngao ngo boi roi'],
      ['Bye nha', 'bye nha tam biet'],
    ],
  },
  {
    id: 'orange-cat',
    label: 'Mèo cam phản ứng',
    color: '#f97316',
    icon: 'fa-cat',
    items: [
      ['Ai làm?', 'ai lam hoi'],
      ['Drama hả?', 'drama ha chuyen'],
      ['Tức á', 'tuc a gian'],
      ['Ngủ bù', 'ngu bu met'],
      ['Mắc cỡ', 'mac co xau ho'],
      ['Hôn nè', 'hon ne yeu'],
      ['Hết pin', 'het pin met'],
      ['Tự ái', 'tu ai gian'],
      ['Sếp gọi', 'sep goi cong viec'],
      ['Mlem nha', 'mlem nha an ngon'],
      ['Không tin nổi', 'khong tin noi bat ngo'],
      ['Bó tay', 'bo tay dau hang'],
      ['Làm ơn', 'lam on please'],
      ['Tỉnh chưa', 'tinh chua hoi'],
      ['Xong chưa', 'xong chua deadline'],
      ['Né ra', 'ne ra tranh'],
    ],
  },
  {
    id: 'office-panda',
    label: 'Panda công sở',
    color: '#475569',
    icon: 'fa-briefcase',
    items: [
      ['Rep liền', 'rep lien tra loi'],
      ['Đã seen', 'da seen doc roi'],
      ['Tò mò quá', 'to mo qua hoi'],
      ['Ổn áp', 'on ap ok'],
      ['Mệt xỉu', 'met xiu met'],
      ['Deadline kia', 'deadline kia cong viec'],
      ['Ngầu chưa', 'ngau chua cool'],
      ['Sạc pin', 'sac pin nghi'],
      ['Hết hồn', 'het hon bat ngo'],
      ['Làm hòa', 'lam hoa xin loi'],
      ['No no', 'no no tu choi'],
      ['Ăn trưa', 'an trua do an'],
      ['Xong chưa', 'xong chua hoi'],
      ['Xin budget', 'xin budget ngan sach'],
      ['Tan làm', 'tan lam het gio'],
      ['Bye nha', 'bye nha tam biet'],
    ],
  },
  {
    id: 'capybara',
    label: 'Capybara thư giãn',
    color: '#a16207',
    icon: 'fa-mug-hot',
    items: [
      ['Đi cà phê', 'di ca phe coffee'],
      ['Mood này', 'mood nay chill'],
      ['Tỉnh chưa', 'tinh chua hoi'],
      ['Cười xỉu', 'cuoi xiu haha'],
      ['Bối rối', 'boi roi lo lang'],
      ['Suy luôn', 'suy luon suy nghi'],
      ['Bé iu', 'be iu yeu'],
      ['Lười ghê', 'luoi ghe nghi'],
      ['Ủa alo', 'ua alo hoi'],
      ['Có thiệt không', 'co thiet khong bat ngo'],
      ['Chắc luôn', 'chac luon dong y'],
      ['Xin nhé', 'xin nhe lam on'],
      ['Đỉnh nha', 'dinh nha proud'],
      ['Thư giãn', 'thu gian chill'],
      ['Ôm cái', 'om cai yeu thuong'],
      ['Bai bai', 'bai bai tam biet'],
    ],
  },
  {
    id: 'duck',
    label: 'Vịt vàng',
    color: '#eab308',
    icon: 'fa-feather-pointed',
    items: [
      ['Quạc nha', 'quac nha xin chao'],
      ['Ủa alo', 'ua alo hoi'],
      ['Hết hồn', 'het hon bat ngo'],
      ['Ngon nha', 'ngon nha an ngon'],
      ['Cạn nước mắt', 'can nuoc mat buon'],
      ['Phèn ghê', 'phen ghe che'],
      ['Bơi đi', 'boi di vui'],
      ['Chạy thôi', 'chay thoi di'],
      ['Quá trời', 'qua troi wow'],
      ['Nghe nè', 'nghe ne hoi'],
      ['Câm nín', 'cam nin im lang'],
      ['Đơ luôn', 'do luon ngan'],
      ['Mắc mưa', 'mac mua buon'],
      ['Thích nha', 'thich nha yeu'],
      ['Nope', 'nope tu choi'],
      ['Tạm biệt', 'tam biet bye'],
    ],
  },
  {
    id: 'pink-bunny',
    label: 'Thỏ hồng đáng yêu',
    color: '#ec4899',
    icon: 'fa-heart',
    items: [
      ['Dỗi nè', 'doi ne gian'],
      ['Tự kỷ', 'tu ky buon'],
      ['Làm hòa', 'lam hoa xin loi'],
      ['Tò mò', 'to mo hoi'],
      ['Đỉnh ghê', 'dinh ghe cool'],
      ['Ngủ ngon', 'ngu ngon chuc ngu ngon'],
      ['Đợi em', 'doi em cho doi'],
      ['Khum chịu', 'khum chiu tu choi'],
      ['Xấu hổ', 'xau ho ngai'],
      ['Sợ nha', 'so nha lo lang'],
      ['Bắn tim', 'ban tim yeu'],
      ['Hết hồn', 'het hon bat ngo'],
      ['Xin lỗi', 'xin loi sorry'],
      ['Yên tâm', 'yen tam ok'],
      ['Mệt xỉu', 'met xiu met'],
      ['Byeee', 'byeee bye'],
    ],
  },
  {
    id: 'bear',
    label: 'Gấu nâu mạnh mẽ',
    color: '#92400e',
    icon: 'fa-paw',
    items: [
      ['Xịn xò', 'xin xo cool'],
      ['Lên đồ', 'len do chuan bi'],
      ['Căng á', 'cang a gian'],
      ['Không ổn', 'khong on roi buon'],
      ['Tin nổi không', 'tin noi khong bat ngo'],
      ['Ngại ghê', 'ngai ghe xau ho'],
      ['Quá đã', 'qua da vui'],
      ['Lẹ lên', 'le len nhanh'],
      ['Bình tĩnh', 'binh tinh calm'],
      ['Hông nhé', 'hong nhe tu choi'],
      ['Thả tim', 'tha tim yeu'],
      ['Coi chừng', 'coi chung canh bao'],
      ['Mlem mlem', 'mlem mlem an ngon'],
      ['Thôi nào', 'thoi nao lam hoa'],
      ['Nghiêm túc', 'nghiem tuc cong viec'],
      ['Tạm biệt', 'tam biet bye'],
    ],
  },
  {
    id: 'otter',
    label: 'Rái cá vui vẻ',
    color: '#0f766e',
    icon: 'fa-water',
    items: [
      ['Buồn chuyện', 'buon chuyen buon'],
      ['Nghe đồn', 'nghe don hoi'],
      ['Ủa thiệt?', 'ua thiet bat ngo'],
      ['Sốc á', 'soc a bat ngo'],
      ['Cười xỉu', 'cuoi xiu haha'],
      ['Hông nè', 'hong ne tu choi'],
      ['Lặn đây', 'lan day bye'],
      ['Ôm tim', 'om tim yeu'],
      ['Ngứa mồm', 'ngua mom khia'],
      ['Adu trời', 'adu troi bat ngo'],
      ['Im lặng', 'im lang khong noi'],
      ['Ngầu nha', 'ngau nha cool'],
      ['Ngáp cái', 'ngap cai met'],
      ['Tê nước', 'te nuoc boi'],
      ['Đỉnh khỏi nói', 'dinh khoi noi cool'],
      ['See ya', 'see ya bye'],
    ],
  },
  {
    id: 'axolotl',
    label: 'Axolotl ngộ nghĩnh',
    color: '#f472b6',
    icon: 'fa-fish',
    items: [
      ['Hi nè', 'hi ne xin chao'],
      ['Bối rối', 'boi roi lo lang'],
      ['Ngơ ngác', 'ngo ngac khong hieu'],
      ['Tự hào', 'tu hao proud'],
      ['Suy nặng', 'suy nang suy nghi'],
      ['Rụng tim', 'rung tim yeu'],
      ['Mlem', 'mlem an ngon'],
      ['Đơ mặt', 'do mat ngan'],
      ['Chán ghê', 'chan ghe met'],
      ['Phát sáng', 'phat sang wow'],
      ['Bơi lẹ', 'boi le nhanh'],
      ['Xỉu xỉu', 'xiu xiu met'],
      ['No nha', 'no nha an no'],
      ['Tới luôn', 'toi luon dong y'],
      ['Xin cảm ơn', 'xin cam on thanks'],
      ['Hẹn gặp', 'hen gap see ya'],
    ],
  },
];

export const STICKER_PACKS = Object.freeze(packDefinitions.map(pack => Object.freeze({
  ...pack,
  items: Object.freeze(pack.items.map(([label, keywords], index) => Object.freeze({
    id: `${pack.id}-${index + 1}`,
    packId: pack.id,
    label,
    keywords,
    src: `${STICKER_ROOT}/${pack.id}-${index + 1}.png`,
    mime: 'image/png',
  }))),
})));

export const STICKER_ITEMS = Object.freeze(STICKER_PACKS.flatMap(pack => pack.items));

export function stickerById(id) {
  return STICKER_ITEMS.find(item => item.id === id) || null;
}

export function stickerPackById(id) {
  return STICKER_PACKS.find(pack => pack.id === id) || null;
}

export function filterStickers(items = STICKER_ITEMS, query = '') {
  const normalized = String(query || '').trim().toLocaleLowerCase('vi');
  if (!normalized) return items;
  return items.filter(item => `${item.label} ${item.keywords}`.toLocaleLowerCase('vi').includes(normalized));
}

export function recentStickerStorageKey(scope = 'anonymous') {
  return `${RECENT_STORAGE_PREFIX}:${String(scope || 'anonymous')}`;
}

export function readRecentStickerIds(scope = 'anonymous') {
  if (typeof window === 'undefined') return [];
  try {
    const value = JSON.parse(window.localStorage.getItem(recentStickerStorageKey(scope)) || '[]');
    return Array.isArray(value)
      ? value.map(id => String(id || '')).filter(id => Boolean(stickerById(id))).slice(0, 24)
      : [];
  } catch {
    return [];
  }
}

export function rememberStickerId(scope, id) {
  const stickerId = String(id || '');
  if (!stickerById(stickerId) || typeof window === 'undefined') return readRecentStickerIds(scope);
  const next = [stickerId, ...readRecentStickerIds(scope).filter(value => value !== stickerId)].slice(0, 24);
  try {
    window.localStorage.setItem(recentStickerStorageKey(scope), JSON.stringify(next));
  } catch {
    // Recent stickers are optional and must never block sending.
  }
  return next;
}
